// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package users

import (
	"database/sql"
)

type User struct {
	ID       int32
	Username sql.NullString
	Email    sql.NullString
	Password sql.NullString
}
